# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sub2cmp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sub2cmp(object):
    def setupUi(self, sub2cmp):
        sub2cmp.setObjectName("sub2cmp")
        sub2cmp.resize(600, 300)
        sub2cmp.setWindowTitle("")
        self.scrollArea = QtWidgets.QScrollArea(sub2cmp)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 600, 300))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.labelSpinBox = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelSpinBox.setGeometry(QtCore.QRect(20, 17, 90, 17))
        self.labelSpinBox.setObjectName("labelSpinBox")
        self.spinBox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox.setGeometry(QtCore.QRect(110, 10, 50, 30))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(5)
        self.spinBox.setObjectName("spinBox")
        self.pushButtonOK = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonOK.setGeometry(QtCore.QRect(170, 15, 30, 20))
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.label1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label1.setGeometry(QtCore.QRect(20, 60, 100, 20))
        self.label1.setObjectName("label1")
        self.pushButton1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton1.setGeometry(QtCore.QRect(120, 58, 80, 24))
        self.pushButton1.setObjectName("pushButton1")
        self.label2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label2.setGeometry(QtCore.QRect(300, 60, 100, 20))
        self.label2.setObjectName("label2")
        self.pushButton2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton2.setGeometry(QtCore.QRect(400, 58, 80, 24))
        self.pushButton2.setObjectName("pushButton2")
        self.labelImg1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelImg1.setGeometry(QtCore.QRect(20, 90, 20, 20))
        self.labelImg1.setText("")
        self.labelImg1.setObjectName("labelImg1")
        self.labelImg2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelImg2.setGeometry(QtCore.QRect(300, 90, 20, 20))
        self.labelImg2.setText("")
        self.labelImg2.setObjectName("labelImg2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(sub2cmp)
        QtCore.QMetaObject.connectSlotsByName(sub2cmp)

    def retranslateUi(self, sub2cmp):
        _translate = QtCore.QCoreApplication.translate
        self.labelSpinBox.setText(_translate("sub2cmp", "Magnitude:"))
        self.pushButtonOK.setText(_translate("sub2cmp", "OK"))
        self.label1.setText(_translate("sub2cmp", "Duplication"))
        self.pushButton1.setText(_translate("sub2cmp", "Write Back"))
        self.label2.setText(_translate("sub2cmp", "Interpolation"))
        self.pushButton2.setText(_translate("sub2cmp", "Write Back"))
