# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subEdgeCrsp.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subEdgeCrsp(object):
    def setupUi(self, subEdgeCrsp):
        subEdgeCrsp.setObjectName("subEdgeCrsp")
        subEdgeCrsp.resize(400, 250)
        self.labelSz = QtWidgets.QLabel(subEdgeCrsp)
        self.labelSz.setGeometry(QtCore.QRect(10, 10, 85, 17))
        self.labelSz.setObjectName("labelSz")
        self.labelImg0 = QtWidgets.QLabel(subEdgeCrsp)
        self.labelImg0.setGeometry(QtCore.QRect(161, 34, 16, 17))
        self.labelImg0.setText("")
        self.labelImg0.setObjectName("labelImg0")
        self.spinBox = QtWidgets.QSpinBox(subEdgeCrsp)
        self.spinBox.setGeometry(QtCore.QRect(95, 7, 45, 25))
        self.spinBox.setMinimum(3)
        self.spinBox.setMaximum(21)
        self.spinBox.setSingleStep(2)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(subEdgeCrsp)
        self.pushButton.setGeometry(QtCore.QRect(10, 210, 30, 25))
        self.pushButton.setObjectName("pushButton")
        self.labelSNR0 = QtWidgets.QLabel(subEdgeCrsp)
        self.labelSNR0.setGeometry(QtCore.QRect(161, 57, 16, 17))
        self.labelSNR0.setText("")
        self.labelSNR0.setObjectName("labelSNR0")
        self.pushButtonWB = QtWidgets.QPushButton(subEdgeCrsp)
        self.pushButtonWB.setGeometry(QtCore.QRect(161, 149, 81, 25))
        self.pushButtonWB.setObjectName("pushButtonWB")
        self.groupBoxKT = QtWidgets.QGroupBox(subEdgeCrsp)
        self.groupBoxKT.setGeometry(QtCore.QRect(10, 35, 120, 80))
        self.groupBoxKT.setAutoFillBackground(False)
        self.groupBoxKT.setFlat(False)
        self.groupBoxKT.setObjectName("groupBoxKT")
        self.radioButtonSqr = QtWidgets.QRadioButton(self.groupBoxKT)
        self.radioButtonSqr.setGeometry(QtCore.QRect(10, 25, 100, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButtonSqr.setIcon(icon)
        self.radioButtonSqr.setAutoExclusive(True)
        self.radioButtonSqr.setObjectName("radioButtonSqr")
        self.radioButtonCrs = QtWidgets.QRadioButton(self.groupBoxKT)
        self.radioButtonCrs.setGeometry(QtCore.QRect(10, 50, 100, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButtonCrs.setIcon(icon1)
        self.radioButtonCrs.setAutoExclusive(True)
        self.radioButtonCrs.setObjectName("radioButtonCrs")
        self.groupBoxMeth = QtWidgets.QGroupBox(subEdgeCrsp)
        self.groupBoxMeth.setGeometry(QtCore.QRect(10, 120, 120, 80))
        self.groupBoxMeth.setFlat(False)
        self.groupBoxMeth.setObjectName("groupBoxMeth")
        self.radioButtonM0 = QtWidgets.QRadioButton(self.groupBoxMeth)
        self.radioButtonM0.setGeometry(QtCore.QRect(10, 25, 60, 25))
        self.radioButtonM0.setAutoExclusive(True)
        self.radioButtonM0.setObjectName("radioButtonM0")
        self.radioButtonM1 = QtWidgets.QRadioButton(self.groupBoxMeth)
        self.radioButtonM1.setGeometry(QtCore.QRect(10, 50, 80, 25))
        self.radioButtonM1.setAutoExclusive(True)
        self.radioButtonM1.setObjectName("radioButtonM1")
        self.label0 = QtWidgets.QLabel(subEdgeCrsp)
        self.label0.setGeometry(QtCore.QRect(161, 11, 74, 17))
        self.label0.setObjectName("label0")
        self.label1 = QtWidgets.QLabel(subEdgeCrsp)
        self.label1.setGeometry(QtCore.QRect(161, 80, 108, 17))
        self.label1.setObjectName("label1")
        self.labelImg1 = QtWidgets.QLabel(subEdgeCrsp)
        self.labelImg1.setGeometry(QtCore.QRect(161, 103, 111, 17))
        self.labelImg1.setText("")
        self.labelImg1.setObjectName("labelImg1")
        self.labelSNR1 = QtWidgets.QLabel(subEdgeCrsp)
        self.labelSNR1.setGeometry(QtCore.QRect(161, 126, 111, 17))
        self.labelSNR1.setText("")
        self.labelSNR1.setObjectName("labelSNR1")

        self.retranslateUi(subEdgeCrsp)
        QtCore.QMetaObject.connectSlotsByName(subEdgeCrsp)

    def retranslateUi(self, subEdgeCrsp):
        _translate = QtCore.QCoreApplication.translate
        subEdgeCrsp.setWindowTitle(_translate("subEdgeCrsp", "Edge crispening"))
        self.labelSz.setText(_translate("subEdgeCrsp", "Kernel size:"))
        self.pushButton.setText(_translate("subEdgeCrsp", "OK"))
        self.pushButtonWB.setText(_translate("subEdgeCrsp", "Write back"))
        self.groupBoxKT.setTitle(_translate("subEdgeCrsp", "Kernel type:"))
        self.radioButtonSqr.setText(_translate("subEdgeCrsp", " Square"))
        self.radioButtonCrs.setText(_translate("subEdgeCrsp", " Cross"))
        self.groupBoxMeth.setTitle(_translate("subEdgeCrsp", "Method:"))
        self.radioButtonM0.setText(_translate("subEdgeCrsp", "Mean"))
        self.radioButtonM1.setText(_translate("subEdgeCrsp", "Median"))
        self.label0.setText(_translate("subEdgeCrsp", "Blur image"))
        self.label1.setText(_translate("subEdgeCrsp", "Edge crispening"))
