# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subGrad.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subGrad(object):
    def setupUi(self, subGrad):
        subGrad.setObjectName("subGrad")
        subGrad.resize(400, 300)
        self.scrollArea = QtWidgets.QScrollArea(subGrad)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 400, 300))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.labelX = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelX.setGeometry(QtCore.QRect(11, 11, 72, 17))
        self.labelX.setObjectName("labelX")
        self.labelY = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelY.setGeometry(QtCore.QRect(89, 11, 52, 17))
        self.labelY.setObjectName("labelY")
        self.labelZ = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelZ.setGeometry(QtCore.QRect(147, 11, 89, 17))
        self.labelZ.setObjectName("labelZ")
        self.labelRoberts = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelRoberts.setGeometry(QtCore.QRect(11, 34, 54, 17))
        self.labelRoberts.setObjectName("labelRoberts")
        self.labelSobel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelSobel.setGeometry(QtCore.QRect(11, 80, 39, 17))
        self.labelSobel.setObjectName("labelSobel")
        self.labelPrewitt = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelPrewitt.setGeometry(QtCore.QRect(11, 126, 51, 17))
        self.labelPrewitt.setObjectName("labelPrewitt")
        self.labelR2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelR2.setGeometry(QtCore.QRect(147, 57, 89, 17))
        self.labelR2.setText("")
        self.labelR2.setObjectName("labelR2")
        self.labelR0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelR0.setGeometry(QtCore.QRect(11, 57, 72, 17))
        self.labelR0.setText("")
        self.labelR0.setObjectName("labelR0")
        self.labelP2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelP2.setGeometry(QtCore.QRect(147, 149, 89, 17))
        self.labelP2.setText("")
        self.labelP2.setObjectName("labelP2")
        self.labelS0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelS0.setGeometry(QtCore.QRect(11, 103, 72, 17))
        self.labelS0.setText("")
        self.labelS0.setObjectName("labelS0")
        self.labelS1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelS1.setGeometry(QtCore.QRect(89, 103, 52, 17))
        self.labelS1.setText("")
        self.labelS1.setObjectName("labelS1")
        self.labelS2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelS2.setGeometry(QtCore.QRect(147, 103, 89, 17))
        self.labelS2.setText("")
        self.labelS2.setObjectName("labelS2")
        self.labelP1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelP1.setGeometry(QtCore.QRect(89, 149, 52, 17))
        self.labelP1.setText("")
        self.labelP1.setObjectName("labelP1")
        self.labelP0 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelP0.setGeometry(QtCore.QRect(11, 149, 72, 17))
        self.labelP0.setText("")
        self.labelP0.setObjectName("labelP0")
        self.labelR1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelR1.setGeometry(QtCore.QRect(89, 57, 52, 17))
        self.labelR1.setText("")
        self.labelR1.setObjectName("labelR1")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(subGrad)
        QtCore.QMetaObject.connectSlotsByName(subGrad)

    def retranslateUi(self, subGrad):
        _translate = QtCore.QCoreApplication.translate
        subGrad.setWindowTitle(_translate("subGrad", "Gradient"))
        self.labelX.setText(_translate("subGrad", "Horizontal"))
        self.labelY.setText(_translate("subGrad", "Vertical"))
        self.labelZ.setText(_translate("subGrad", "2-Dimesional"))
        self.labelRoberts.setText(_translate("subGrad", "Roberts"))
        self.labelSobel.setText(_translate("subGrad", "Sobel"))
        self.labelPrewitt.setText(_translate("subGrad", "Prewitt"))
