# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'subMean.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_subMean(object):
    def setupUi(self, subMean):
        subMean.setObjectName("subMean")
        subMean.resize(400, 270)
        self.labelSz = QtWidgets.QLabel(subMean)
        self.labelSz.setGeometry(QtCore.QRect(10, 10, 85, 17))
        self.labelSz.setObjectName("labelSz")
        self.labelImg = QtWidgets.QLabel(subMean)
        self.labelImg.setGeometry(QtCore.QRect(160, 20, 20, 20))
        self.labelImg.setText("")
        self.labelImg.setObjectName("labelImg")
        self.spinBox = QtWidgets.QSpinBox(subMean)
        self.spinBox.setGeometry(QtCore.QRect(95, 7, 45, 25))
        self.spinBox.setMinimum(3)
        self.spinBox.setMaximum(21)
        self.spinBox.setSingleStep(2)
        self.spinBox.setObjectName("spinBox")
        self.pushButton = QtWidgets.QPushButton(subMean)
        self.pushButton.setGeometry(QtCore.QRect(10, 125, 30, 25))
        self.pushButton.setObjectName("pushButton")
        self.labelSNR = QtWidgets.QLabel(subMean)
        self.labelSNR.setGeometry(QtCore.QRect(160, 200, 200, 20))
        self.labelSNR.setText("")
        self.labelSNR.setObjectName("labelSNR")
        self.pushButtonWB = QtWidgets.QPushButton(subMean)
        self.pushButtonWB.setGeometry(QtCore.QRect(160, 220, 80, 20))
        self.pushButtonWB.setObjectName("pushButtonWB")
        self.groupBoxKT = QtWidgets.QGroupBox(subMean)
        self.groupBoxKT.setGeometry(QtCore.QRect(10, 35, 120, 80))
        self.groupBoxKT.setAutoFillBackground(False)
        self.groupBoxKT.setFlat(False)
        self.groupBoxKT.setObjectName("groupBoxKT")
        self.radioButtonSqr = QtWidgets.QRadioButton(self.groupBoxKT)
        self.radioButtonSqr.setGeometry(QtCore.QRect(10, 25, 100, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButtonSqr.setIcon(icon)
        self.radioButtonSqr.setAutoExclusive(True)
        self.radioButtonSqr.setObjectName("radioButtonSqr")
        self.radioButtonCrs = QtWidgets.QRadioButton(self.groupBoxKT)
        self.radioButtonCrs.setGeometry(QtCore.QRect(10, 50, 100, 25))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/cross.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButtonCrs.setIcon(icon1)
        self.radioButtonCrs.setAutoExclusive(True)
        self.radioButtonCrs.setObjectName("radioButtonCrs")

        self.retranslateUi(subMean)
        QtCore.QMetaObject.connectSlotsByName(subMean)

    def retranslateUi(self, subMean):
        _translate = QtCore.QCoreApplication.translate
        subMean.setWindowTitle(_translate("subMean", "Lowpass filter"))
        self.labelSz.setText(_translate("subMean", "Kernel size:"))
        self.pushButton.setText(_translate("subMean", "OK"))
        self.pushButtonWB.setText(_translate("subMean", "Write back"))
        self.groupBoxKT.setTitle(_translate("subMean", "Kernel type:"))
        self.radioButtonSqr.setText(_translate("subMean", " Square"))
        self.radioButtonCrs.setText(_translate("subMean", " Cross"))
